name: Test and Qodana Analysis

on:
  push: # Trigger on pushes to the repo
    branches:
      - main              # Specify the branch to run the workflow on
  pull_request:           # Also trigger on pull requests
  workflow_dispatch:

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      # Step 2: Set up your environment (Python example)
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install dependencies required for running tests
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 3: Run tests
      - name: Run tests
        run: |
          pytest --cov=. --cov-report=html || exit 1  # Replace with the test framework or command for your project

      # Step 4: Run Qodana analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3.4
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1667823880 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

      #      # Step 5: Publish Qodana report (optional)
      - name: Upload Qodana Report
        uses: actions/upload-artifact@v4.6.0
        with:
          name: coverage-report
          path: htmlcov/   # Directory where the coverage HTML report is generated